name: merge to main
on:
  push:
    branches:
        main

permissions: 
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Setup artifact directory
        run: make init
        continue-on-error: false
      # - name: Setup localstack
      #   run: make test-setup
      - name: Run tests
        run: make test
        continue-on-error: false
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: .test/
  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/download-artifact@v4
        with:
          run-id: ${{ needs.test.outputs.run_id }}
          name: artifacts
          path: .test/
      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0.3.0
        with:
          report: true
          chart: true
          amend: true
