name: test
on:
  push:
    branches:
        main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: .test/
      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0.3.0
        with:
          report: true
          chart: true
          amend: true